Wizard app
pavle-prelic-ey/ProjectMars pull request #3
Opened 2021-07-16 08:42 UTC by pavle-prelic-ey

2021-07-19 09:33 UTC, MilanovicM requested changes
### Pavle, awesome job! The application looks great.  I really like the look and feel, and all the details - including spinner and the progress bar. Well done!
The folders are neatly organized, and kudos for using more advance concepts like - useReducer, multiple Context providers, etc...
I'm requesting changes because I wasn't able to save applicant at the end - I got 400 bad request. I suspect that you need to call different API if the applicant has no convictions. I've heard from other team members that Milos and Marija solved this, so maybe they can provide more details on this. 
As I said, that's just my assumption, so it's better if you look into that failing request again :)
Another thing that could be improved is the vertical scroll inside of carousel cards. The text inside of them would look better shortened, or maybe with "see more" or "...". 
This would improve the UX for sure ;)

Great work, again 💯

2021-07-19 09:33 UTC, MilanovicM commented on src/components/Step3/StepThree.js
> +      return counter + 1;
Use implicit return here :)

2021-07-19 09:33 UTC, MilanovicM commented on src/components/Step3/StepThree.js
> +    axios
Please see the previous comment about service abstraction.

2021-07-19 09:33 UTC, MilanovicM commented on src/components/Step3/StepThree.js
> +                ></textarea>
This can be a self closing tag.

2021-07-19 09:33 UTC, MilanovicM commented on src/components/Step3/StepThree.js
> +                <div className="input_check_wrapper">
These inputs here are basically all the same - except for the name and value. Maybe we could create some array with only those three values as [marketing, cutting, drilling, etc] and use map function to return input for each entry? That way we would reduce number of code lines, and if we want to add some more skills here, we don't need to write new code - just add an entry to array :)

2021-07-19 09:33 UTC, MilanovicM commented on src/components/Step3/StepThree.js
> +            <InputHeading labelTitle={"Have you ever been convicted?"} />
Please see previous comments about passing text as prop.

2021-07-19 09:33 UTC, MilanovicM commented on src/components/ValidateSteps/ValidateStepOne.js
> +  const errors = { validated: true };
This file shouldn't be inside of components folder  -this is more of a helper function.

2021-07-19 09:33 UTC, MilanovicM commented on src/components/ValidateSteps/ValidateStepTwo.js
> +const ValidateStepTwo = ({ email, residencyDuration }) => {
Please see comment for ValidateStepOne.js. These validation functions could maybe be one service for form validation? 
Also, the regex used could be kept inside of constants, for reusability and easier code maintenance.

2021-07-19 09:33 UTC, MilanovicM commented on src/components/WIzardHeader/WizardHeader.js
> +  return (
Please use implicit return here :)

2021-07-19 09:33 UTC, MilanovicM commented on src/consts/statesUrl.js
> +export const stateUrl = "http://det.api.rs.ey.com/";
Good job on keeping URL in a separate file. The file name could be more generic, so we can store all potential URLs that we might add in the future.

2021-07-19 09:33 UTC, MilanovicM commented on src/customHooks/useFetch.js
> +    } catch (error) {
If the code in try block fails, will setLoading(false) ever get triggered? Should that be added inside of catch block?

2021-07-19 09:33 UTC, MilanovicM commented on src/sharedFunctions/debouncFunction.js
> +const debounceFunction = (func, delay) => {
Are we using this function elsewhere? Just asking :)

2021-07-22 06:51 UTC, MilanovicM commented
Hi Pavle, I couldn't start the application - there is an error 
![image](https://user-images.githubusercontent.com/46046446/126599875-8f0efcba-158a-4ddf-b4c7-f4eec38701cb.png)
I think that the path to the file got broken.

2021-07-22 10:53 UTC, MilanovicM reviewed
### Pavle, PR looks great :) Great job on adding tests. 

Please see my comments, there are still a few things to improve. Also, I've noticed that Address line 2 filed is marked as required, and I think it shouldn't be required. 
There are a few typos here and there, e.g. adress (d is missing), Biycicle, etc. There is Code Spell Checker extension for Visual Studio Code - maybe that can help :)

Awesome work!

2021-07-22 10:53 UTC, MilanovicM commented on src/App.js
> +  useFetch(`${url}?api_key=${key}&count=${limit}`);
What is the purpose of this useFetch function call? We are receiving loading, error and data from useFetch hook. Not sure if we store the values anywhere.

2021-07-22 10:53 UTC, MilanovicM commented on src/Helpers/ValidateSteps/ValidateStepOne.js
> +  if (!firstName.trim()) {
These two code blocks are basically the same (4-9). Maybe we can move that to separate function, which will validate first and last name?

2021-07-22 10:53 UTC, MilanovicM commented on src/api/xhr.js
> +
Good job on abstracting xhr service ;)

2021-07-23 06:23 UTC, MilanovicM requested changes
### Pavle, the application looks really good. The code is also structured well, easy to read and understand!! Great job!

There are two small things that I've noticed -
1. if we choose negative residency years, and then change it to 0, it will pass the validation (the submit button will remain enabled). When that goes to BE, we get error response:
errors: {residencyDuration: ["The residency duration must be at least 1."]}
residencyDuration: ["The residency duration must be at least 1."]
message: "The given data was invalid."
2. if we have spacing in the name input - there is an error saying "Please enter text"

I think both can be easily fixed :)

2021-07-26 06:20 UTC, MilanovicM approved these changes
### Pavle, awesome job! 
The application looks and works great! 🥇 Bravo!!!

2021-07-26 07:05 UTC, merged

2021-07-26 07:06 UTC, pavle-prelic-ey commented
> ### Pavle, awesome job!
> The application looks and works great! 🥇 Bravo!!!

Thank you!